/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#081837",
        "on-primary": "#ffffff",
        "primary-container": "#1f2d4d",
        "on-primary-container": "#8795bb",
        "inverse-primary": "#b8c6ee",
        "secondary": "#466083",
        "on-secondary": "#ffffff",
        "secondary-container": "#b9d3fd",
        "on-secondary-container": "#415b7f",
        "tertiary": "#001c29",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#003246",
        "on-tertiary-container": "#00a0d8",
        "surface": "#f7f9fc",
        "on-surface": "#191c1e",
        "surface-variant": "#e0e3e6",
        "on-surface-variant": "#45464e",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f7",
        "surface-container": "#eceef1",
        "surface-container-high": "#e6e8eb",
        "surface-container-highest": "#e0e3e6",
        "surface-dim": "#d8dadd",
        "surface-bright": "#f7f9fc",
        "outline": "#75777f",
        "outline-variant": "#c5c6cf",
        "surface-tint": "#505e81",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f4",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#d9e2ff",
        "primary-fixed-dim": "#b8c6ee",
        "on-primary-fixed": "#0b1a3a",
        "on-primary-fixed-variant": "#384668",
        "secondary-fixed": "#d3e3ff",
        "secondary-fixed-dim": "#aec8f1",
        "on-secondary-fixed": "#001c39",
        "on-secondary-fixed-variant": "#2d486a",
        "tertiary-fixed": "#c4e7ff",
        "tertiary-fixed-dim": "#7bd0ff",
        "on-tertiary-fixed": "#001e2c",
        "on-tertiary-fixed-variant": "#004c69",
        "background": "#f7f9fc",
        "on-background": "#191c1e",
        // Dark Mode tokens
        "dark-bg": "#070b14",
        "dark-surface": "#0d1424",
        "dark-surface-card": "rgba(15, 23, 42, 0.65)",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
      spacing: {
        "stack-xs": "4px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "24px",
        "stack-xl": "32px",
        "gutter": "24px",
        "panel-padding": "24px",
        "margin-screen": "32px"
      },
      fontFamily: {
        "sans": ["Inter", "system-ui", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "label-md": ["JetBrains Mono", "monospace"],
        "tabular-nums": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "body-md": ["13px", { "lineHeight": "18px", "fontWeight": "400" }],
        "body-lg": ["15px", { "lineHeight": "22px", "fontWeight": "400" }],
        "headline-md": ["18px", { "lineHeight": "24px", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "headline-lg": ["22px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-xl": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "tabular-nums": ["13px", { "lineHeight": "18px", "letterSpacing": "0px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
